### ISSUE TITLE
OSError [Errno 48] Address already in use

### ISSUE THREAD

**Issue by Suekru** [nneonneo/iOS-SOCKS-Server#10]
As far as I understand this means that python thinks the port is already in use, however, even when switching the port in the code this error will keep popping up. In non jailbroken state when this error happens I just have to restart the phone and it'll usually work after that. But for some reason in jailbroken state on ios 14.5.1, it will always give this error no matter what I do. I'm not sure what the issue could be, it works fine on ios 13.5 with/without jailbreak.

**Comment by nneonneo** [comment]
The program doesn’t always exit cleanly; if it doesn’t, the socket may not be closed. In that case, force-closing Pythonista and reopening it should solve the problem. 

As for jailbroken devices, my best guess is that you have some service which is occupying the port. You may consider using netstat to identify the service, or just change the port in the code. 

Note that this program uses two ports, so you may need to change both; I recommend picking random numbers between 16384 and 30000.
