### ISSUE TITLE
Not working for Mac OS 14

### ISSUE THREAD

**Issue by dan2889** [nneonneo/iOS-SOCKS-Server#12]
Hi there I’ve tried to get this working on my os Mac but having issues, wanted to see if you could help, thanks :)

**Comment by nneonneo** [comment]
Thanks for your comment! I'll need some more details to help, although I'll caution that I'm still rocking macOS 12 so I may not be able to fully debug the issue.

- Have you tried the detailed instructions here: https://github.com/nneonneo/iOS-SOCKS-Server/issues/1#issuecomment-1566498055 (note, updated from the original instructions earlier in the thread). This setup has been tested to work fine on my machine, but has not been extensively tested with every version of macOS.

- What exact version are you running, and on what hardware?
- What iOS version are you running, on what hardware, and what network are you on?
- How are you connecting your Mac to your iOS device - real tethering (WiFi or USB), ad-hoc network, or shared WiFi network?
- What is the output from the proxy? Only the first part is relevant (where it prints the interfaces and IP addresses).
- Are you able to access the "PAC URL" (wpad.dat) from your Mac? It should download or display a small text file when accessed from your Mac's web browser.

**Comment by Poxios** [comment]
@dan2889 
Are you using the native proxy settings in mac os? If so, some apps may be able to use the network without going through the proxy.
  
To solve this, you can use [proxifier](https://www.proxifier.com/download/) or [tun2socks](https://github.com/xjasonlyu/tun2socks) that forces all traffic to pass through a proxy.

**Comment by hellodaniel** [comment]
@dan2889 This issue needs better definition. I've been using on macOS 14 Sonoma for at least 4 months without issue. The only obvious thing I can think of is that some browsers, notably Firefox, may use their own proxy settings.

**Comment by nneonneo** [comment]
@Abestren this is an iOS limitation: applications cannot run in the background outside of a limited number of exceptions, such as navigation (background location) or playing music. As far as I understand it, apps require special entitlements to run in the background, but Pythonista doesn't have these entitlements so scripts cannot run while in the background. (If you have any clever ideas to work around this limitation, I'm all ears!)

**Comment by nneonneo** [comment]
I'm going to close this issue, as @dan2889 has not replied in a while and it seems to work fine for others. Please feel free to file a new issue if you continue to have issues.
