### ISSUE TITLE
Backgrounding

### ISSUE THREAD

**Issue by bro2baseball** [nneonneo/iOS-SOCKS-Server#5]
First of all, thanks so much for this solution. It works great. I use Proxifier to route all my computer traffic through the proxy. 

But in order to keep the connection active, I need to keep the Pythonista window open on my phone and the screen on. Is there any way around this, or is it just a limitation of that app? Thanks again.

**Comment by nneonneo** [comment]
It's a limitation of the app - apps on iOS cannot background for longer than a few seconds. (There are workarounds with things like background location permissions - but I would rather not go down that way).
