### ISSUE TITLE
Google Meet Does Not Work While Connected to Proxy

### ISSUE THREAD

**Issue by xeemzor** [nneonneo/iOS-SOCKS-Server#6]
Whenever I try to use google meet for video conferences while connected to this proxy the connection does not work.  I am able to join, but can't hear or see anyone.  The connection then disconnects after 15-30 seconds with an error about a firewall.

This can be replicated by attempting to join any meeting through the https://meet.google.com/ service while connected to the proxy.

Is it possible to fix this proxy to work with google meet?

**Comment by nneonneo** [comment]
Unfortunately, it looks like Google Meet does not currently support SOCKS5 proxies such as this one. From [their documentation](https://support.google.com/a/answer/1279090?hl=en#zippy=%2Cstep-set-up-outbound-ports-for-media-traffic%2Cqos-best-practices%2Cwi-fi-best-practices%2Cusing-proxies):

> We strongly recommend that you do not use proxy servers for Meet traffic. 
> ...
> The Socket Secure (SOCKS5) internet protocol is not currently supported.
